name:                elle
version:             0.1.0.0
github:              "stnma7e/elle"
license:             BSD3
author:              "Sam Delmerico"
maintainer:          "svdelmerico@gmail.com"
copyright:           "2019 Sam Delmerico"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stnma7e/elle#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2 && < 2.3
- parsec >= 3.1 &&  < 3.2
- hspec >= 2.7 && < 2.8
- QuickCheck >= 2.13 && < 2.14
- pretty >= 1.1.3 && < 1.1.4

library:
  source-dirs: src

executables:
  elle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O0
    - -Wall
    - -rtsopts=all
    - -prof
    - -auto-all
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-1
    dependencies:
    - elle

tests:
  elle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elle
